
services:
  weaviate:
    image: semitechnologies/weaviate:1.24.8
    ports:
      - "8080:8080"       # REST API
      - "50051:50051"     # gRPC
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
    env_file:
      - .env  
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env

